import type { RegistryServer } from "./registry.js";

/**
 * A real snapshot of the public MCP registry (registry.modelcontextprotocol.io
 * /v0/servers), fetched and trimmed to the fields the readiness scan uses. Real data
 * so the scan grades genuine servers, fully offline and deterministic; a live drop-in
 * (`fetchRegistryLive`) pages the same API for a fresh pull.
 */
export const REGISTRY_SNAPSHOT: RegistryServer[] = [
  {
    name: "ac.inference.sh/mcp",
    description:
      "Run 150+ AI apps — image, video, audio, LLMs, 3D and more. Browse, execute, stream results",
    hasRepository: false,
    remoteTypes: ["streamable-http", "streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ac.inference.sh/mcp",
    description:
      "Run 150+ AI apps — image, video, audio, LLMs, 3D and more. Browse, execute, stream results",
    hasRepository: false,
    remoteTypes: ["streamable-http", "streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
  {
    name: "ac.tandem/docs-mcp",
    description:
      "Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.3.0",
  },
  {
    name: "ac.tandem/docs-mcp",
    description:
      "Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.3.1",
  },
  {
    name: "ac.tandem/docs-mcp",
    description:
      "Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.3.2",
  },
  {
    name: "ag.hood/name-service",
    description:
      "Resolve .hood names on Robinhood Chain — forward/reverse, text records, availability & pri",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "agency.lona/trading",
    description:
      "AI-powered trading strategy development: backtesting, market data, and portfolio analysis",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "2.0.0",
  },
  {
    name: "ai.1325/mcp",
    description:
      "Verified directory of 44,000+ Black-owned U.S. businesses. Search, maps, loyalty rewards.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.aarna/atars-mcp",
    description:
      "Crypto market signals, technical indicators, and sentiment analysis for AI agents.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.abmeter/abmeter",
    description:
      "Feature flagging and A/B testing platform with AI-first experimentation workflows.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.adadvisor/mcp-server",
    description:
      "Query Meta Ads performance data — accounts, campaigns, ad sets, ads, metrics & settings.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.adadvisor/mcp-server",
    description:
      "Query Meta Ads performance data — accounts, campaigns, ad sets, ads, metrics & settings.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
  {
    name: "ai.adeu/adeu",
    description: "Automated DOCX Redlining Engine",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "1.5.2",
  },
  {
    name: "ai.adeu/adeu",
    description: "Automated DOCX Redlining Engine",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "1.7.1",
  },
  {
    name: "ai.adramp/google-ads",
    description: "Google Ads MCP server — manage campaigns, keywords, and metrics.",
    hasRepository: true,
    remoteTypes: ["sse"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.adramp/google-ads",
    description: "Google Ads MCP server — manage campaigns, keywords, and metrics.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.1",
  },
  {
    name: "ai.adramp/google-ads",
    description: "Google Ads MCP server — manage campaigns, keywords, and metrics.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.2",
  },
  {
    name: "ai.adramp/google-ads",
    description: "Google Ads MCP server — manage campaigns, keywords, and metrics.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.3",
  },
  {
    name: "ai.adweave/meta-ads-mcp",
    description:
      "Meta Ads MCP server with 47 tools for campaigns, creatives, audiences, and insights.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.agentberg/agentberg",
    description:
      "Agent-to-agent trading intelligence exchange. Publish findings, vote on quality, earn repu",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.2.0",
  },
  {
    name: "ai.agentdm/agentdm",
    description: "Agent-to-agent messaging platform using MCP for cross-model communication.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.agentdm/agentdm",
    description:
      "Agent communication platform for agent to agent messaging via MCP. Messages, channels, ski",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "2.0.0",
  },
  {
    name: "ai.agentic-news/mcp",
    description:
      "AI-powered news intelligence — 21 tools for personalized monitoring, briefings, and semant",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.agenticshelf/graffeo",
    description:
      "Live MCP catalog for Graffeo Coffee Roasting — North Beach SF specialty coffee since 1935.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "deprecated",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.agenticshelf/graffeo",
    description:
      "Live MCP catalog for Graffeo Coffee Roasting - Simply the World's Finest Coffee since 1935",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "deprecated",
    isLatest: false,
    version: "1.0.1",
  },
  {
    name: "ai.agenticshelf/graffeo",
    description:
      "Live MCP catalog for Graffeo Coffee Roasting - Simply the World's Finest Coffee since 1935",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.2",
  },
  {
    name: "ai.agenticshelf/mcp",
    description:
      "Hosted MCP for e-commerce: live product catalog, stock, and pricing for AI agents.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.agenticshelf/puroair",
    description:
      "Live MCP catalog for PuroAir HEPA-14 air purifiers - real-time stock, pricing, and details",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.agenticshelf/puroair",
    description:
      "Breathe with Confidence. Live MCP catalog for PuroAir HEPA air purifiers - stock, pricing,",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
  {
    name: "ai.agenticterminal/directory",
    description:
      "Verified merchants accepting agentic payments on Lightning/L402/BOLT12/USDT — search, veri",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.agentrapay/agentra",
    description:
      "Identity oracle and trust layer for autonomous AI agents. Bidirectional KYA and trust scor",
    hasRepository: true,
    remoteTypes: ["sse"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.agenttrust/mcp-server",
    description:
      "Identity, trust, and A2A orchestration for autonomous AI agents. Official A2A partner.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "1.1.1",
  },
  {
    name: "ai.aient/mcp",
    description:
      "MCP-native AI SRE: ask what's broken in production, get a reviewed GitHub fix PR.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.airshelf/catalog",
    description:
      "Cross-vendor B2B catalog for AI agents: search, compare, find equivalents, request a quote",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.aisecuritygateway/mcp-gateway",
    description:
      "Security & DLP proxy for MCP: tool-poisoning scans, PII redaction on tool args/results. Be",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.aliengiraffe/spotdb",
    description: "Ephemeral data sandbox for AI workflows with guardrails and security",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.alphacreek/alphacreek-mcp",
    description: "Access SEC filings efficiently, save time and tokens, and get cited answers.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.alphacreek/alphacreek-mcp",
    description:
      "Access SEC filings efficiently (10-K, 10-Q, etc), save time and tokens, and get cited answ",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
  {
    name: "ai.alpic.mcp/alpic-mcp",
    description:
      "Manage your projects, debug deployment, and check analytics for any MCP server you host wi",
    hasRepository: false,
    remoteTypes: ["streamable-http", "sse"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.0.1",
  },
  {
    name: "ai.alpic.test/test-mcp-server",
    description: "Alpic Test MCP Server - great server!",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.0.1",
  },
  {
    name: "ai.ambix/ambix",
    description:
      "Your product team's shared strategic memory — an MCP server your AI tools reason over.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.18.4",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.18.4-tunnel",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.18.5",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.19.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.19.1",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.19.2",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.20.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.20.1",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.21.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.22.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "0.22.1",
  },
  {
    name: "ai.ankimcp/anki-mcp-server",
    description:
      "MCP server for Anki flashcards: adaptive review, notes, media, and deck management via Ank",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.22.2",
  },
  {
    name: "ai.ankimcp/anki-mcp-server-addon",
    description:
      "Anki addon that exposes your flashcard collection to AI assistants via a local MCP server.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.15.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server-addon",
    description:
      "Anki addon that exposes your flashcard collection to AI assistants via a local MCP server.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.15.1",
  },
  {
    name: "ai.ankimcp/anki-mcp-server-addon",
    description:
      "Anki addon that exposes your flashcard collection to AI assistants via a local MCP server.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.17.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server-addon",
    description:
      "Anki addon that exposes your flashcard collection to AI assistants via a local MCP server.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "0.18.0",
  },
  {
    name: "ai.ankimcp/anki-mcp-server-addon",
    description:
      "Anki addon that exposes your flashcard collection to AI assistants via a local MCP server.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.19.0",
  },
  {
    name: "ai.anomalyarmor/armor-mcp",
    description:
      "Data observability tools for engineering teams: alerts, freshness, schema drift, lineage, ",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.6.1",
  },
  {
    name: "ai.anzenna/anzenna",
    description: "MCP server for Anzenna",
    hasRepository: true,
    remoteTypes: ["sse"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1",
  },
  {
    name: "ai.apithreshold/apithreshold",
    description:
      "Quality scoring and progressive gates for AI-generated API tests. Stripe/Twilio profiles. ",
    hasRepository: false,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.appdeploy/deploy-app",
    description:
      "AppDeploy turns app ideas described in AI chat into live full-stack web applications",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.arclan/registry",
    description:
      "MCP server registry — validated by live handshake, scored on reliability, monitored contin",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.argushq/enforcement-database",
    description:
      "Search Argus HQ public FDA enforcement data: warning letters, recalls, approvals, 483s.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.arpi/arpi-mcp",
    description:
      "AI-powered ECG analysis: submit ECG images and receive diagnosis reports from ARPI's ECG A",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.artidrop/artidrop",
    description:
      "The publishing layer for AI agents. Turn HTML and Markdown into shareable URLs instantly v",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.artidrop/artidrop",
    description:
      "Publish HTML, Markdown, and multi-file sites as shareable URLs instantly via MCP.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.1.0",
  },
  {
    name: "ai.assetlog/assetlog",
    description:
      "Search and manage AssetLog listings: vehicles, real estate, jobs, CVs, favorites, AI promp",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.atdev/supershopping",
    description:
      "나만을 위한 AI 쇼핑 MCP — 상품을 자연어로 검색·비교·추천해 사용자의 효과적인 쇼핑을 돕습니다.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.augmentev/paseo",
    description:
      "Confidential AI execution with a post-quantum receipt on every job — verifiable by anyone.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.auralogs/auralogs",
    description:
      "Read-only access to Auralogs production logs: search logs, inspect errors, review AI analy",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.auteng/docs",
    description:
      "Publish markdown documents as public share links with mermaid diagram support. Built by Au",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.1.0",
  },
  {
    name: "ai.auteng/mcp",
    description: "Publish markdown as a publicly shareable AutEng document",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.auteng/mcp",
    description:
      "Publish markdown documents as public share links with mermaid diagrams. Built by AutEng.ai",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
  {
    name: "ai.autoblocks/contextlayer-mcp",
    description: "Personal context management for AI assistants",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.0.3",
  },
  {
    name: "ai.autoblocks/ctxl",
    description: "Personal context management for AI assistants",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.0.2",
  },
  {
    name: "ai.autoblocks/ctxl-mcp",
    description: "Personal context management for AI assistants",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "0.0.2",
  },
  {
    name: "ai.autonomad/computeback",
    description:
      "Agent marketplace: earn $NOMD on B2B work, spend on compute/voice/memory capabilities.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: false,
    version: "1.1.2",
  },
  {
    name: "ai.autonomad/computeback",
    description: "Agent Rewards Marketplace: earn $NOMD on B2B work, spend on agent capabilities.",
    hasRepository: true,
    remoteTypes: [],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "1.1.3",
  },
  {
    name: "ai.autonomad/travel",
    description:
      "AI travel agent — book flights, hotels, activities, and events worldwide via autonomad.ai.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 1,
    status: "active",
    isLatest: true,
    version: "1.4.0",
  },
  {
    name: "ai.autorfp/mcp",
    description:
      "Search AutoRFP.ai projects, requirements, content library, and tags for Q&A and analytics.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.auxen/auxen",
    description:
      "Provision private AI model endpoints on dedicated GPUs (Llama, Qwen, Mistral). Pay per min",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.auxen/auxen",
    description:
      "Provision private AI model endpoints on dedicated GPUs (Llama, Qwen, Mistral). Pay per min",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.1",
  },
  {
    name: "ai.auxen/auxen",
    description:
      "Provision private AI model endpoints on dedicated GPUs (Llama, Qwen, Mistral). Pay per min",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.2",
  },
  {
    name: "ai.aviado/health",
    description:
      "Supplement research, biomarker effects, drug interactions, and brand quality data",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.1.0",
  },
  {
    name: "ai.axonagentic/neuroautomata",
    description:
      "Protein analysis: ESM-2/ESMC embeddings, mutation scoring, landscape scans, ESMFold struct",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "0.29.0",
  },
  {
    name: "ai.backengine/backengine-mcp",
    description:
      "Surface customer & prospect context from Slack, email, transcripts and tickets in any MCP ",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.backengine/backengine-mcp",
    description:
      "Surface customer & prospect context from Slack, email, transcripts and tickets in any MCP ",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "8.0.3",
  },
  {
    name: "ai.backengine/backengine-mcp",
    description:
      "Surface customer & prospect context from Slack, email, transcripts and tickets in any MCP ",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "8.0.4",
  },
  {
    name: "ai.backengine/backengine-mcp",
    description:
      "Surface customer & prospect context from Slack, email, transcripts and tickets in any MCP ",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "8.1.1",
  },
  {
    name: "ai.bankee/inferventis-mcp",
    description:
      "Loan & mortgage calculator, compound interest, ROI, crypto prices, FX conversion for AI ag",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.2",
  },
  {
    name: "ai.bareun/bareun",
    description:
      "Korean NLP MCP server: morphological analysis, tokenization, spell & grammar checking (Bar",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "3.0.0",
  },
  {
    name: "ai.baselight/baselight",
    description:
      "Query Baselight's public catalog of 70,000+ datasets — finance, demographics, sports, and ",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.basethread/basethread",
    description:
      "One shared context your team's AI tools read & write over MCP. No re-explaining. Free.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.benroberts/b4-index",
    description:
      "Independent build-vs-buy index: score software categories BUILD/BUY/BRIDGE/BEWARE.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "3.3.0",
  },
  {
    name: "ai.betterpost/server",
    description:
      "Finds timely sources across news, social, and the web and writes posts worth publishing.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.betterpost/server",
    description:
      "Finds timely sources across news, social, and the web and writes posts worth publishing.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "2.0.0",
  },
  {
    name: "ai.bezal/local-commerce",
    description:
      "Search 7,000+ local service businesses across America by category, location, or keyword.",
    hasRepository: false,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.0",
  },
  {
    name: "ai.biddeed/biddeed-mcp",
    description: "AI-powered foreclosure auction intelligence for Florida counties via MCP tools.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: false,
    version: "1.0.0",
  },
  {
    name: "ai.biddeed/biddeed-mcp",
    description: "AI-powered foreclosure auction intelligence for Florida counties via MCP tools.",
    hasRepository: true,
    remoteTypes: ["streamable-http"],
    packageCount: 0,
    status: "active",
    isLatest: true,
    version: "1.0.1",
  },
];
