import type { Business } from "../types.ts";
import type { LocaleCode, Strings } from "../i18n/strings.ts";
import { stringsFor } from "../i18n/strings.ts";
import { outputSlug, slugify } from "../generate/util.ts";
import { jsonLdScript } from "../generate/schema.ts";
import { ogImageSvg } from "../generate/ogimage.ts";
import { analyticsSnippet, hasAnalytics, type AnalyticsOptions } from "../generate/analytics.ts";
import { generateWxr } from "./wxr.ts";
import { generateTheme, themeSlug } from "./theme.ts";
import { generateProvisionScript } from "./provision.ts";
import { generateComposerJson } from "./composer.ts";
import { generateProductsCsv } from "./woocommerce.ts";
import { resolvePlugins, type ResolvedPlugin } from "./plugins.ts";

export interface BundleFile {
  /** Path relative to the business's bundle directory. */
  path: string;
  content: string;
  /** Mark scripts so the writer can chmod +x. */
  executable?: boolean;
}

export interface WordPressBundle {
  slug: string;
  files: BundleFile[];
  plugins: ResolvedPlugin[];
  themeSlug: string;
  locale: LocaleCode;
}

export interface BundleOptions {
  strings?: Strings;
  baseTheme?: string;
  /** Live WP.org plugin lookup (best-effort). */
  livePlugins?: boolean;
  /** Analytics providers (GA4 / Plausible) for a wp_head mu-plugin. */
  analytics?: AnalyticsOptions;
  fetchImpl?: typeof fetch;
}

/**
 * Assemble a complete, deployable WordPress site bundle for a business:
 *  - content.wxr.xml   → importable content (pages + reviews)
 *  - theme/<slug>/…    → block child theme (theme.json palette + front-page)
 *  - provision.sh      → WP-CLI: core + language + theme + plugins + import
 *  - composer.json     → roots/wordpress + wpackagist (Composer path)
 *  - plugins.json      → resolved WordPress.org plugin slugs + rationale
 *  - wp-cli.yml        → WP-CLI config
 *  - README.md         → three ways to deploy
 */
export async function generateWordPressBundle(
  business: Business,
  opts: BundleOptions = {},
): Promise<WordPressBundle> {
  const s = opts.strings ?? stringsFor("en");
  const baseTheme = opts.baseTheme ?? "twentytwentyfour";
  const slug = outputSlug(business);
  const plugins = await resolvePlugins(business, {
    fetchImpl: opts.fetchImpl,
    live: opts.livePlugins,
  });
  const theme = generateTheme(business, s, baseTheme);
  const tSlug = themeSlug(business);

  const files: BundleFile[] = [
    { path: "content.wxr.xml", content: generateWxr(business, s) },
    ...theme,
    {
      path: "provision.sh",
      content: generateProvisionScript(business, s, { plugins, baseTheme }),
      executable: true,
    },
    { path: "composer.json", content: generateComposerJson(business, { plugins, baseTheme }) },
    {
      path: `mu-plugins/${slugify(business.name)}-schema.php`,
      content: schemaMuPlugin(business, s),
    },
    { path: `assets/${slugify(business.name)}.og.svg`, content: ogImageSvg(business, s) },
    { path: "plugins.json", content: JSON.stringify(plugins, null, 2) + "\n" },
    { path: "wp-cli.yml", content: `path: .\napache_modules:\n  - mod_rewrite\n` },
  ];

  if (opts.analytics && hasAnalytics(opts.analytics)) {
    files.push({
      path: `mu-plugins/${slugify(business.name)}-analytics.php`,
      content: analyticsMuPlugin(business, opts.analytics),
    });
  }

  // Retail businesses (WooCommerce resolved) get a starter product CSV.
  if (plugins.some((p) => p.slug === "woocommerce")) {
    files.push({ path: "woocommerce/products.csv", content: generateProductsCsv(business, s) });
  }

  files.push({
    path: "README.md",
    content: bundleReadme(business, s, { plugins, baseTheme, themeSlug: tSlug }),
  });

  return { slug, files, plugins, themeSlug: tSlug, locale: s.code };
}

function bundleReadme(
  business: Business,
  s: Strings,
  ctx: { plugins: ResolvedPlugin[]; baseTheme: string; themeSlug: string },
): string {
  const pluginList = ctx.plugins.map((p) => `- \`${p.slug}\` — ${p.reason}`).join("\n");
  return `# WordPress site — ${business.name}

Auto-generated by biz-site-builder from ${business.name}'s public profile${
    business.reviews.length ? ", images and community reviews" : ""
  }. Language: **${s.code === "he" ? "Hebrew (he_IL, RTL)" : "English (en_US)"}**.

## Contents

| File | Purpose |
| --- | --- |
| \`content.wxr.xml\` | WordPress import: Home / About / Reviews / Contact pages + reviews as comments |
| \`theme/${ctx.themeSlug}/\` | Block child theme of \`${ctx.baseTheme}\` (palette from the brand colour + front-page template) |
| \`provision.sh\` | WP-CLI: download core, install ${s.code === "he" ? "Hebrew" : "English"} language, theme, plugins, import content |
| \`composer.json\` | roots/wordpress + wpackagist dependencies (Composer path) |
| \`plugins.json\` | Resolved WordPress.org plugin slugs |
| \`wp-cli.yml\` | WP-CLI config |

## Deploy — pick one

### 1. WP-CLI (fastest, full site)
\`\`\`bash
DB_NAME=wp DB_USER=root DB_PASS=secret SITE_URL=https://${themeHost(business)} bash provision.sh
\`\`\`

### 2. Composer (manage as a project)
\`\`\`bash
composer install         # pulls WordPress core + plugins + base theme
# then copy theme/${ctx.themeSlug} into wp-content/themes and import content.wxr.xml
\`\`\`

### 3. Manual import (existing WordPress)
Upload \`theme/${ctx.themeSlug}\`, activate it, then **Tools → Import → WordPress** and
upload \`content.wxr.xml\`.

## Plugins (from the WordPress.org directory)
${pluginList}
`;
}

function themeHost(business: Business): string {
  return `${outputSlug(business).replace(/-[a-z0-9]{1,6}$/, "")}.example`;
}

/**
 * A must-use plugin that prints schema.org LocalBusiness JSON-LD in `wp_head`.
 * Drop the mu-plugins/ folder into wp-content/ (mu-plugins auto-activate).
 */
function schemaMuPlugin(business: Business, s: Strings): string {
  const script = jsonLdScript(business, s);
  return `<?php
/**
 * Plugin Name: ${business.name} — Structured Data
 * Description: schema.org LocalBusiness JSON-LD for SEO. Generated by biz-site-builder.
 */
if (!defined('ABSPATH')) {
    exit;
}
add_action('wp_head', function () {
    echo <<<'BSB_SCHEMA'
${script}
BSB_SCHEMA;
    echo "\\n";
});
`;
}

/** A must-use plugin that injects the analytics snippet into `wp_head`. */
function analyticsMuPlugin(business: Business, analytics: AnalyticsOptions): string {
  const snippet = analyticsSnippet(business, analytics);
  return `<?php
/**
 * Plugin Name: ${business.name} — Analytics
 * Description: Injects analytics (GA4 / Plausible). Generated by biz-site-builder.
 */
if (!defined('ABSPATH')) {
    exit;
}
add_action('wp_head', function () {
    echo <<<'BSB_ANALYTICS'
${snippet}
BSB_ANALYTICS;
    echo "\\n";
});
`;
}
