import type { Business } from "../types.ts";
import type { ResolvedPlugin } from "./plugins.ts";
import { themeSlug } from "./theme.ts";

/**
 * Generate a Composer manifest for the site using the roots/wordpress core
 * package and wpackagist (the Composer mirror of the WordPress.org plugin/theme
 * directories). This is the "Composer path" to the same site the WP-CLI script
 * provisions — for teams that manage WordPress as a Composer project.
 */
export function generateComposerJson(
  business: Business,
  opts: { plugins: ResolvedPlugin[]; baseTheme: string },
): string {
  const require: Record<string, string> = {
    php: ">=8.1",
    "composer/installers": "^2.0",
    "roots/wordpress": "^6.5",
    [`wpackagist-theme/${opts.baseTheme}`]: "*",
  };
  for (const p of opts.plugins) require[`wpackagist-plugin/${p.slug}`] = "*";

  const manifest = {
    name: `biz-site-builder/${themeSlug(business).replace(/-theme$/, "")}`,
    description: `WordPress site for ${business.name}, generated by biz-site-builder.`,
    type: "project",
    repositories: [{ type: "composer", url: "https://wpackagist.org" }],
    require,
    extra: {
      "installer-paths": {
        "wp-content/plugins/{$name}/": ["type:wordpress-plugin"],
        "wp-content/themes/{$name}/": ["type:wordpress-theme"],
      },
      "wordpress-install-dir": "wp",
    },
    config: {
      "allow-plugins": { "composer/installers": true, "roots/wordpress-core-installer": true },
    },
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}
